
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { mockPredictions } from '../../data/mockData';

interface ThreatPredictorProps {
  className?: string;
}

const ThreatPredictor: React.FC<ThreatPredictorProps> = ({ className }) => {
  return (
    <Card className={className}>
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center">
          <span className="bg-theme-purple-600 w-2 h-2 rounded-full mr-2 animate-pulse"></span>
          AI Predictions
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-3">
          {mockPredictions.map((prediction) => (
            <div 
              key={prediction.id} 
              className="p-3 rounded-md border border-theme-dark-500 bg-theme-dark-700/50"
            >
              <div className="flex items-center mb-2">
                <div className="w-2 h-2 rounded-full bg-theme-purple-500 mr-2"></div>
                <p className="text-xs text-theme-purple-300">
                  {prediction.confidence}% Confidence
                </p>
              </div>
              <p className="text-sm">{prediction.text}</p>
              <div className="mt-2 flex justify-between items-center">
                <span className="text-xs text-muted-foreground">Impact: {prediction.impact}</span>
                <span className="text-xs text-muted-foreground">Timeframe: {prediction.timeframe}</span>
              </div>
            </div>
          ))}
        </div>
        <div className="mt-4 text-xs text-center text-muted-foreground">
          These predictions are generated by AI based on current events and historical patterns.
        </div>
      </CardContent>
    </Card>
  );
};

export default ThreatPredictor;
