
import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { mockPredictions } from '../../data/mockData';

interface ThreatPredictorProps {
  className?: string;
}

const ThreatPredictor: React.FC<ThreatPredictorProps> = ({ className }) => {
  return (
    <Card className={className}>
      <CardHeader className="pb-2">
        <CardTitle className="flex items-center tracking-wide">
          <span className="bg-theme-purple-600 w-3 h-3 rounded-full mr-3 animate-pulse"></span>
          AI Predictions
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="space-y-6">
          {mockPredictions.map((prediction) => (
            <div 
              key={prediction.id} 
              className="p-5 rounded-lg border border-theme-dark-500 bg-theme-dark-700/50"
            >
              <div className="flex items-center mb-3">
                <div className="w-3 h-3 rounded-full bg-theme-purple-500 mr-3"></div>
                <p className="text-sm text-theme-purple-300 tracking-wide">
                  {prediction.confidence}% Confidence
                </p>
              </div>
              <p className="text-base tracking-wide leading-relaxed">{prediction.text}</p>
              <div className="mt-4 flex justify-between items-center">
                <span className="text-sm text-muted-foreground">Impact: {prediction.impact}</span>
                <span className="text-sm text-muted-foreground">Timeframe: {prediction.timeframe}</span>
              </div>
            </div>
          ))}
        </div>
        <div className="mt-8 text-sm text-center text-muted-foreground leading-relaxed">
          These predictions are generated by AI based on current events and historical patterns.
        </div>
      </CardContent>
    </Card>
  );
};

export default ThreatPredictor;
